export const data = [
  {
    id: 1,
    img: 'child.jpg',
    name: 'CHILD HEALTH SCREEN',
    desc: 'Random Blood Glucose, CBC+ESR,Biluribin-total,     Blood Group & RH,     Mantoux Test, Urine Routine, Chest X-Ray,     BMI',
    price: 'RS=850',
    detail:
      'Newborns get their first screening tests soon after they re born. Then children are screened for different things at each routine checkup or sick visit, and even at school. Your state or county may require that children get certain screening tests too As kids and teens grow and change, there’s a lot to keep track of. So, health care providers screen for different things at different times in a child’s life. They can do this in different ways',
    branch: 'MAVELIKARA',
    address: 'Near Govt. Hospital Mavelikara',
    image: '.doctor.jpg',
    im: '100 ma.webp',
    nam: 'Siemens X Ray Machnes - 100 MA / 160 MA and 200 MA        ',
    des: 'The X-Ray Machine.The heart of an X-ray machine is an electrode pair a cathode and an anode that sits inside a glass vacuum tube.',
    giph: 'https://www.cdc.gov/dotw/covid-19/images/main_928px.jpg',
    link: 'Post-COVID Health ',
    date:'04-MARCH-2023',
    
    para:'Research is still ongoing to know about the post-COVID-19 effecton people.Doctors are closely monitoring people who have had COVID-19 to see how their organs are functioning after recovery Many large medical centershave also opened specialized clinics to provide care for people who present persistent symptoms or related illnesses after they recover from COVID-19. Support groups are also working parallelly.  Most people who had COVID-19 recovered quickly. But the long-lasting problems of COVID-19 have made it even more important to reduce the spread of this pandemic and mandatorily calls by following precautions.  A subset of people who ve recovered from COVID-19 is experiencing symptoms that linger beyond testing negative for the virus. These individuals are referred to as "COVID long-haulers."  COVID-19 symptoms can sometimes persist for months. The virus has the potential to damage human organs such as the lungs, heart and brain leading to long-term health problems  The older the younger and the otherwise healthy people are all commonly mentioning about feeling unwell for weeks to months even after recovering from the infection.',
    head1:'Common signs and symptoms that linger over time include:    ',
    para1:'Fatigue, Shortness of breath or difficulty breathing, Cough, Joint pain, Chest pain. Memory, concentration,or sleep problems, Muscle pain or headache. Fast or pounding heartbeat,Loss of smell or taste, Depression or anxiety,Fever, Dizziness when you stand,Worsened symptoms after physical or mental activities',
    head2:'The risk of developing post-COVID syndrome is higher on:    ',
    para2:'There have been cases of organ damage caused by COVID-19 as well. Although the disease primarily affects the lungs, other organs, including the heart, kidneys, and the brain are also subject to damage.  Organ damage if any also leads to health complications that linger after COVID-19 illness. The lasting health effects in some people included long-term breathing problems, heart complications, chronic kidney impairment, stroke, and Guillain-Barre syndrome (a condition that causes temporary paralysis). Some adults and children also complained about experiencing multisystem inflammatory syndrome after they had COVID-19.',
    head3:'Bottomline ',
    para3:'Post-COVID syndrome is a newphenomenon, and studies are still revolving around it. But doctors know its symptoms, particularly the extreme fatigue which can have huge downstream effects on a person s quality of life, and impact his family life and work productivity.Specialty doctors and hospitals who are working as a team have a unique goal to help such people manage their lingering symptoms as effectively as possible. The clinic also focuses on performing impactful research and provides doctors with access to those tools that can help tailor care to the specific treatments someone previously received or the particular strain of the virus he or she was infected with. Lastly, it s all the more reason to continue to take the essential steps to reduce your risk of getting sick.',
    doctor:'https://wallpaperset.com/w/full/9/2/0/455904.jpg',
    docname:'DR.Joseph Kuruvila (MBBS, DIABATOLOGIST)',
  },
  {
    id: 2,
    img: 'rrr.jpg',
    name: 'ROUTINE CHECKUP',
    desc: 'Fasting Blood Glucose, PP Blood Glucose, Lipid Profile Tests,  Bilirubin,Urea,Creatinine,CBC+ ESR,,BMI,Blood Pressure',
    price: 'RS=1130',
    detail:
      'A routine or regular health checkup consists of an overall physical examination and tests that help assess the functionality of the heart, lungs, digestive system, kidneys, liver & immune system It assists in evaluating a person’s current health condition, including identifying any apparent symptoms, warning signs or abnormalities inside the body',
    branch: 'Vytla',
    address: 'Near Lakeshore Hospital, Vytla',
    im: 'Gamma-counter-3.jpg',
    nam: 'Automated 12 Well Gamma Counters        ',
    des: 'Automatic Gamma Counter is the premier measurement system for high energy gamma emitters, as well as low level gamma activity and environmental samples, suitable especially well for sophisticated research in nuclear medicine',
    giph: 'https://www.medivision.in/uploaded_files/blog/istockphoto-1360823624-612x612_1676720955.jpg',
    link: 'Bile Acid Estimation',
    date:'18-FEBRUARY-2023',

    para:'Bile acids are a component of bile and are a large family of molecules that have a steroidal structure. Bile acids are made in the liver and stored in the gall bladder, which help with the digestion of foods, particularly fat. Whenever food is eaten, the body sends a signal to the gall bladder to contract and push bile acids into the small intestine. It is synthesized from cholesterol in the liver and is actively secreted along with cholesterol and phospholipids into the bile. Bile acids play a key role in human metabolism. It facilitates the digestion and absorption of lipids, maintains the dissolved state of cholesterol in bile, and inhibits its precipitation. Bile acids also act as signalling molecules to regulate self-metabolism, lipid metabolism, energy balance, and glucose metabolism by binding to the “membrane bile acid receptor.”',
    head1:'Significance of bile acid    ',
    para1:'Bile that is flowing from the liver is concentrated in the gallbladder. It is released into the upper intestine each time in response to a meal. Once it reaches the intestines, bile acids act as detergents helping to emulsify fats, and aiding in their digestion and absorption.  After digestion in the small bowel, bile acids are completely (almost 95%) reabsorbed in the distal ileum and later retaken up from portal blood by the liver (enterohepatic circulation).  The primary bile acids that are synthesized in the liver are cholic and chenodeoxycholic acid and are typically conjugated to glycine or taurine before secretion. In the intestine, colonic bacteria often convert the primary bile acids to secondary bile acids, predominantly deoxycholic acid and lithocholic acid. The reabsorbed bile acids are then transported to the liver in portal blood. Conjugated bile acids are retaken by hepatocytes via the sodium taurocholate cotransporter (NTCT). The unconjugated bile acids are taken by organic anion transporters that also take up bilirubin and other anions.   The total bile acid pool in humans is controlled by coordinated regulation of the expression of genes involved with the synthesis, secretion, reabsorption, and reuptake of bile acids by the liver. ',
    head2:'Interpretation of bile acid test',
    para2:'If the liver is healthy and functioning, the bile acids levels will be low in the resting blood sample and only slightly higher levels of bile acids will be there in the postprandial sample. This indicates that bile acids released from the gall bladder during the test meal were adequately recaptured by the liver during the 2-hour period following the meal. Hence the conclusion from the test will be that the liver has enough cells to do its job, there is a blood supply, and bile is flowing properly. But a normal result needn’t always mean the liver is completely healthy. Because, sometimes the bile acid test results will show normal, even when there is a problem in the liver. This happens when the problem is mild or affects only a small portion of the liver.In such situations, there is often no reduction in the overall ability of the liver to do its job. In other situations, the gall bladder may not contract as expected, and bile acids levels will be low, even though a liver problem may exist',
    head3:'Conclusion    ',
    para3:'Bile acid tests are highly helpful in understanding if the bile and the liver are functioning well. If the bile acid test is abnormal, the result indicates that there is a problem in the liver. Depending on how sick the person is and how abnormal the test results are, the doctor may recommend monitoring the situation, or may suggest moving on to additional diagnostic tests including an ultrasound of the liver, and possibly a liver biopsy.',
    doctor:'https://wallpapercave.com/wp/wp2469723.jpg',
    docname:'Dr.Rajeev Philp (ONCOLOGIST)',
  },
  {
    id: 3,
    img: 'Diabetes-Checkup-1-585x400.jpg',
    name: 'DIABETIC CHECKUP',
    desc: 'Fasting Blood Glucose,PP Blood Glucose, Lipid Profile,   HBA1C, Urea,  Creatinine, CBC+ESR,   Urine Routine,ECG,BMI',
    price: 'RS=1400',
    detail:
      'People who take control of their own diabetes care by eating healthy foods, living an active lifestyle, and taking medicines as prescribed often have good control of their blood sugar levels. Still, regular health checkups and tests are needed',
    branch: 'Panampallinagar',
    address: 'Near Medical Trust Hospital,panampallinagar-Cochin',
    im: 'vitros-250-ortho-make--500x500.webp',
    nam: 'Vitros 250    ',
    des: 'The Ortho Clinical Vitros 250 Chemistry System is a flexible system that can function as a single routine and STAT analyzer a dedicated system for STATs or esoterics',
    giph: 'https://www.medivision.in/uploaded_files/blog/istockphoto-627356286-612x612_1674813006.jpg',
    link: '(DCT & ICT',
    date:'27-January-2023',

    para:'The Coombs test is a blood test that enables to check for those antibodies that attack red blood cells. The test is also called an antiglobulin test or red blood cell antibody screening.   This is an immunology laboratory procedure that is used to detect the presence of antibodies against circulating red blood cells (RBCs) in the body.There are two types of Coombs tests. The direct test looks for antibodies that are stuck to red blood cells. The indirect test looks for antibodies floating in the liquid part of your blood, called serum.',
    head1:'Indirect Coombs Test    ',
    para1:'Indirect antiglobulin testing (IAT) also known as Indirect Coombs Test, is used to detect unbound antibodies to RBCs, which may be present in the patient’s serum.The indirect Coombs test looks for antibodies that are floating in the blood, which could potentially act against certain red blood cells. This test is most often done to determine if one shows a reaction to a blood transfusion. The person’s blood will be checked before doing a transfusion to make sure it doesnt have antibodies that would react badly to the donated blood. It s part of the "type and screen" process.Pregnant women will get a prenatal antibody screening with an indirect Coombs test. It checks the mothers blood to see if there are antibodies that could pass to and harm the unborn baby.',
    head2:'Direct Coombs Test    ',
    para2:'A direct Coombs test, or direct antiglobulin testing DAT, helps to detect why a person has symptoms that suggest trouble related to their blood.The direct Coombs test can detect antibodies that are stuck to the surface of red blood cells due to certain diseases and/or the usage of certain drugs. In such cases, the antibodies sometimes destroy the red blood cells causing anaemia. In such cases, a direct coombs test will be recommended to test for signs or symptoms of anaemia or jaundice.You might get sick after a blood transfusion if the donors blood wasnt a good match. Your body may recognize those other blood cells as foreign and make antibodies to get rid of them, even though theyre meant to help.',
    head3:'Conclusion    ',
    para3:'The Coombs test is effective in checking your blood for antibodies that attack red blood cells. This test may is usually used to screen your blood before a procedure, such as a blood transfusion or to find out if you have certain conditions, such as autoimmune haemolytic anaemia.',
    doctor:'https://c4.wallpaperflare.com/wallpaper/232/159/577/adult-doctor-girl-healthcare-wallpaper-thumb.jpg',
    docname:'Dr. Neethu Jerrin (GYNECOLOGIST)',
  },
  {
    id: 4,
    img: 'masterhealthcheckup.jpg',
    name: 'GENERAL TEST',
    desc: 'CBC+ESR,Random Blood Glucose,Liver Function Tests,Kidney Function Tests,Lipid Profile Tests,Thyroid Function Tests (T3,T4,TSH),Urine Routine Examination,ECG,BMI,Blood Pressure',
    price: 'RS=1990',
    detail:
      'Whenever anybody wants a general body checkup as a preventive measure, the following tests may be advised, which may help rule out some abnormalities in the body system.This may be advised once a year for everybody',
    branch: 'Parumala',
    address: 'Near Parumala Hospital, Thikkappuzha, Pathanamtitta',
    im: 'Ortho-AutoVue-Innova-Systeem_Hematologie_6981_5-1.jpeg',
    nam: 'Ortho Autovue (Blood Group analyser)',
    des: 'he ORTHO AutoVue Innova is a fully automated system that will enhance the ability to achieve accurate results and will enhance the operational efficiency in your laboratory',
    giph: 'https://www.medivision.in/uploaded_files/blog/istockphoto-1247879942-612x612_1673951330.jpg',
    link: 'Know Your Thyroid Health With Timely Diagnosis',
    date:'17-January-2023',

    para:'The thyroid gland is a vital hormone that plays a major role in the human bodys metabolism, growth, and development. The thyroid gland regulates many body functions by constantly releasing a steady amount of thyroid hormones into the bloodstream. Whenever the body needs more energy in instances like growth or getting a cold, or while pregnant, the thyroid gland produces more hormones.',
    head1:'What causes thyroid disease?    ',
    para1:'Thyroid disease is a general term for a medical condition wherein the thyroid gland doesn’t make the right amount of hormones. If the thyroid gland makes either too much or too little hormones, it leads to thyroid disease. There are different types of thyroid disease, including hyperthyroidism, hypothyroidism, thyroiditis, and Hashimoto’s thyroiditis. Improper thyroid gland functioning can impact your entire body. Too much thyroid hormone causes hyperthyroidism and too little thyroid hormone can lead to hypothyroidism. Both these conditions are serious and need treatment.',
    head2:'TSH test    ',
    para2:'    Checks the amount of TSH in the blood first. TSH is a hormone made in the pituitary gland that tells the thyroid how much T4 and T3 to make.A high TSH level indicates hypothyroidism, or an underactive thyroid, meaning the thyroid isn’t making enough hormone. As a result, the pituitary keeps making and releasing TSH into the blood. A low TSH level usually means, hyperthyroidism, or an overactive thyroid. This occurs when the thyroid is making too much hormone, so the pituitary stops making and releasing TSH into the blood. If the TSH test results are not normal, you will need at least one other test to help find the cause of the problem.',
    head3:'To Conclude    ',
    para3:'If youre feeling tired for no reason or if you have other symptoms of suspected thyroid disease, it is wise to diagnose and understand your thyroid health. Just because you’re not showing any signs or symptoms of a thyroid disorder, also doesn’t mean it’s not there. Catching a thyroid nodule early on can decrease your chances of developing an overactive thyroid. Early detection also helps to treat more serious conditions including thyroid cancer.A regular and timely diagnosis helps with knowing and maintain your thyroid health. ',
    doctor:'https://wallpapercave.com/wp/wp2469732.jpg',
    docname:'Dr. Veena kumar Iyer (ORTHO)',
  },
  {
    id: 5,
    img: 'gen.jpg',
    name: 'COMPREHENSIVE HEALTH CHECKUP',
    desc: 'Fasting Blood Glucose,PP Blood Glucose,Bilirubin,SGPT,Urea,Creatinine,Lipid Profile,Thyroid Function Tests (T3, T4, TSH),CBC + ESR,Urine Complete Analysis,ECG,Ultrasound Scanning – Whole Abdomen',
    price: 'RS=2570',
    detail:
      'A full medical checkup, or full body checkup, is a comprehensive clinical assessment or examination done by a doctor. It can include a medical examination, pathology tests, medical imaging and more.',
    branch: 'Kottayam',
    address: 'Near Kottayam Medical College, Kottayam',
    im: 'eeg-machine-500x500.jpg',
    nam: 'EEG        ',
    des: 'Electroencephalography is an electrophysiological monitoring method to record electrical activity of the brain.It is typically noninvasive with the electrodes placed along the scalp',
    giph: 'https://www.medivision.in/uploaded_files/blog/istockphoto-1431350450-612x612_1672468596.jpg',
    link: 'PIVKA-II - A Cancer Marker For The Liver',
    date:'31-DECEMBER-2022',

    para:'Liver cancer is sometimes referred to as a “silent disease” because early liver cancer often doesn’t cause symptoms. As it grows, symptoms start becoming prominent. Liver cancer is unique in that it occurs mostly in people who have some liver damage.The most common type of primary liver cancer is Hepatocellular carcinoma (HCC). The risk of hepatocellular carcinoma is higher in people with long-term liver diseases and is also higher if the liver is scarred by infection with hepatitis B or hepatitis C.  Hepatocellular carcinoma is also observed in people who drink large amounts of alcohol and have fat accumulation in the liver.',
    head1:'Common risk factors    ',
    para1:'Viral Hepatitis,Cirrhosis,  Inherited Metabolic Diseases,  Diabetes and Obesity,  Anabolic Steroids,  Arsenic poisoning ',
    head2:'Diagnosis of hepatocellular carcinoma by usual means is done through    ',
    para2:'Blood tests to measure liver function, Imaging tests, such as CT and MRI, Liver biopsy, in some cases, to remove a sample of liver tissue for laboratory testing',
    head3:'To Conclude    ',
    para3:'The degree of liver damage plays a very important role in determining what treatment options are possible for an individual patient. Treatment for liver cancer has the most favourable outcome when detected and treated in the early stages before it has spread. Cancer marker like PIVKA-II has a significant role to play in the apt diagnosis of the condition of your liver. ',
    doctor:'https://wallpapercave.com/wp/wp2968613.jpg',
    docname:'Dr.Zaem Ali Ahamed  (PHYSICIAN)',
  },
  {
    id: 6,
    img: 'WomensHealthCheckup_Share.jpg',
    name: 'HEALTHY LADY CHECUP PACKAGE',
    desc: 'Fasting Blood Glucose,PP Blood Glucose,Cholesterol,Urine Routine Examination,CBC + ESR,ECG,Chest X-Ray,Ultrasound Scan- Whole Abdomen,Mammography (Both Breasts)',
    price: 'RS=3320',
    detail:
      'As it is rightly said ‘a woman is the backbone of the family’. She manages both fronts; personal as well as professional with equal amount of energy, determination and vigor. Taking care of the family as well as managing the work in a company, women s list of responsibilities are never-ending. With all these demanding tasks; a woman is more prone to physical, mental, biological factors that may result into stressful and hazardous life thus making a female health check-up vital',
    branch: 'Vandanam',
    address: 'Near Medical College , Alappuzha, Vandanam',
    im: 'bone.jpg',
    nam: 'Bone densitometry scanner        ',
    des: 'A bone densitometry scan measures the calcium content in the bones,which cannot be evaluated in an ordinary X-ray.Although an X-ray may appear to show that the',
    giph: 'https://www.medivision.in/uploaded_files/blog/istockphoto-1252698935-612x612_1671436698.jpg',
    link: 'Thyroid Antibodies - A Silent Problem Marker for Thyroid Gland ',
    date:'19-DECEMBER-2022',


    para:'In response to a foreign invasion in our body like in form of viruses or bacteria, certain proteins are formed in the blood that protects us from these foreign substances. These are known as antibodies. But sometimes antibodies attack the bodys cells, tissues, and organs by mistake creating an autoimmune response.    ',
    head1:'What are thyroid antibodies?    ',
    para1:'Likewise, thyroid antibodies develop in a person’s body, when the immune system mistakenly attacks the thyroid cells and tissues. This in turn leads to inflammation, tissue damage, or disrupted thyroid function. These antibodies can then cause autoimmune thyroid disorders, such as Graves’ disease and Hashimoto’s thyroiditis.Hence, when thyroid antibodies attack healthy thyroid cells, it leads to an autoimmune disorder of the thyroid. These disorders can in turn cause serious health problems if not treated.There are different types of thyroid antibodies. Some antibodies destroy thyroid tissue. Others cause the thyroid to make too much of certain thyroid hormones.',
    head2:'Who needs to test?    ',
    para2:'You may need this test if you have symptoms of a thyroid problem and your provider thinks they may be caused by Hashimoto disease or Graves disease. Symptoms of Hashimoto’s disease include: --Weight gain,Fatigue,Hair loss,Low tolerance for cold temperatures,  Irregular menstrual periods,Constipation,Depression,Joint pain',  
    head3:'Key Takeaway    ',
    para3:'The presence of antibodies is used as an indicator to confirm the diagnosis of autoimmune thyroid diseases. In certain cases, some people will test positive for more than one type of thyroid antibody and it is also possible to test positive for thyroid antibodies even without having thyroid disease. The presence of antibodies in a person with borderline thyroid disease can indicate the possibility of developing full-blown thyroid disease.  Hence, getting tested and treated is better than being ignorant!',
    doctor:'https://media.gettyimages.com/videos/updating-patient-files-online-video-id1200051236?s=640x640',
    docname:'Dr.Sherin S  (GYNECOLOGIST)',
  },

  {
    id: 7,
    img: 'kidneys-red-blue-drawing.jpg',
    name: 'KIDNEY HEALTH SCREENING',
    desc: 'Fasting Blood Glucose,PP Blood Glucose, Kidney Function TesT,   Electrolytes,Nefro-C (Cystatin-C),Microalbuminuria,CBC + ESR',
    price: 'RS=3870',
    detail:
      'You can help lower your risk for CKD or keep it from getting worse by eating healthy, being active, and keeping your blood pressure and cholesterol levels in your target range. Make sure to take care of your kidneys if you are at risk for CKD. If you have diabetes, get tested for kidney disease once each year. Having your kidneys checked regularly gives you the best chance for finding and treating CKD early.',
    branch: 'Tiruvalla',
    address: 'Near MarThoma Sabha Office, Tiruvalla, Pathanamtitta',
    im: 'ecg.jpg',
    nam: 'ECG        ',
    des: 'The ECG is the most commonly performed cardiac test.This is because the ECG is a useful screening tool for a variety of cardiac abnormalities and the test is simple',
    giph: 'https://www.medivision.in/uploaded_files/blog/istockphoto-1205214936-612x612_1669374089.jpg',
    link: 'Breast Cancer - Don’t Make Losing an Option Make Screening A Decision',
    date:'14-NOVEMBER-2022',

    para:'Precautionary checking of a woman’s breasts for cancer even before there are signs or symptoms of the disease is known as breast cancer screening. Various screening options are available for the same and some guidelines mention the recommended age-wise checking',
    head1:'Why is screening important    ',
    para1:'The two most important strategies for preventing deaths from breast cancer are early diagnosis and getting appropriate treatment. Getting regular screening tests is the most reliable way to find breast cancer early.   Tests and exams help find signs of breast cancer even in people who don’t have any symptoms. The goal of screening tests for breast cancer is to find it early before it causes symptoms (like a lump in the breast that can be felt).  Breast cancers that are detected during screening exams are more likely to be smaller and less likely to have spread outside the breast. The size of breast cancer and how far it has spread are some of the most important factors in predicting the prognosis (outlook) of a woman with this disease.',
    head2:'Imaging Tests to Find Breast Cancer    ',
    para2:'Different tests help to look for and diagnose breast cancer. If your doctor finds an area of concern on a screening test (a mammogram), or if you have symptoms that could mean breast cancer, you will need more tests to know for sure if it’s cancer, such as: ',
    head3:'To Conclude    ',
    para3:'Breast cancer is sometimes found after symptoms appear, but many women with breast cancer have no symptoms. This is why regular breast cancer screening is so important. Screening can often help find breast cancer early before any symptoms appear. Finding breast cancer early gives you a better chance of successful treatment. ',
    doctor:'https://th.bing.com/th/id/OIP.23Lt5grZzKct1ZmgGGmbpwHaE7?w=244&h=180&c=7&r=0&o=5&pid=1.7',
    docname:'Dr.Farhana (GASTRO)',
  },
  {
    id: 8,
    img: 'exc male.webp',
    name: 'SENIOR CITIZEN CHECKUP(MALE)',
    desc: 'Fasting Blood Glucose,PP Blood Glucose, Urea,PSA, ECG, BMI, Creatinine',
    price: 'RS=3920',
    detail:
      'The proverb health is wealth is true through and through. And one of the best ways to prevent illnesses and health conditions is to have an annual health checkup without fail If your age has exceeded 60 years, then you need a rather comprehensive health checkup compared to standard checkups',
    branch: 'Anchal',
    address: 'Near St Joseph College,Anchal-kollam',
    im: 'mammography-machine-500x500.jpg',
    nam: 'Mammogram        ',
    des: 'A mammogram is a special type of X-ray of the breasts.Mammograms can show tumors long before they are big enough for you or your health care provider to feel',
    giph: 'https://www.medivision.in/uploaded_files/blog/istockphoto-1338376003-612x612_1668394484.jpg',
    link: 'Let Sweetness Be In Your Character, Not In Your Blood!',
    date:'02-NOVEMBER-2022',

    para:'Today is World Diabetes Day (WDD) also marking the birthday of Sir Frederick Banting, who co-discovered insulin along with Charles Best in 1922.WDD is the world’s largest diabetes awareness campaign reaching a global audience of over 1 billion people in more than 160 countries. The theme for World Diabetes Day 2021-23 is access to diabetes care, emphasizing the f',
    head1:' The term diabetes is not new, but how much do we know about it?    ',
    para1:'Diabetes is a chronic metabolic disease wherein the body doesn’t make enough insulin causing too much blood sugar in the bloodstream and resulting in long-lasting health conditions. A combination of genetic and lifestyle factors is said to trigger diabetes in a person.The earlier to treat and manage diabetes is only when the earliest it’s caught. It can be difficult to recognize the signs if you’re unsure of what to watch for. Feeling thirstier often, frequent urination, losing weight without diet or exercise, feeling tired, weak, irritable or having other mood changes, blurry vision, slow-healing sores, and easily prone to infections, such as gum, skin and vaginal infections, are all the “not to miss signs.”',
    head2:' Diabetes is a singular name, but the types are many    ',
    para2:'Each type of diabetes has a different cause. An autoimmune reaction of the body where the body attacks itself by mistake and destroys the insulin-producing beta cells in the pancreas causes Type 1 diabetes. Genes could be a reason for this and there is also a possibility that a virus sets off an immune system attack. In type 2 diabetes, the body doesn’t use insulin well and can’t keep blood sugar at normal levels. Around 90-95% of people with diabetes are tested as type 2 diabetic.  A combination of genetics and lifestyle factors can lead to Type 2 diabetes. In some cases, hormonal changes during pregnancy can cause another form of diabetes known as Gestational diabetes. Certain hormones produced by the placenta make a pregnant person’s cells less sensitive to the effects of insulin causing high blood sugar during pregnancy. Yet another type is Prediabetes, a condition where the blood sugar levels are higher than normal, but not high enough for a type 2 diabetes diagnosis. With Prediabetes the risk for type 2 diabetes, heart disease, and stroke are higher.',
    head3:' Combat the complications of diabetes    ',
    para3:'Diabetes complications are disabling, develop gradually, and can have long-term effects. The longer you have diabetes, the less controlled will be your blood sugar, resulting in a higher risk of complications. The commonest complications include cardiovascular disease, atherosclerosis, nerve damage, kidney failure, visual disturbance, and even depression. The deadliest complication is ketoacidosis where the patient lands up in the emergency department with vomiting, fast breathing, body aches headache, and breathing difficulties. Hence it is important to monitor and control blood glucose',
    doctor:'https://phoenixsoldiers.org/images/privacy-act-bc-document-retention.jpg',
    docname:'Dr.Akhil G(ORTHO SPCIALIST)',
  },
  {
    id: 9,
    img: 'senior female.jpg',
    name: 'SENIOR CITIZEN CHECKUP(FEMALE)',
    desc: 'Fasting Blood Glucose,PP Blood Glucose, Urea,, ECG, BMI, Creatinine',
    price: 'RS=3860',
    detail:
      'For female senior citizens, we carry out a thorough checkup that includes mammography, ECG, ophthalmology consultation, audiogram and ENT consultation, cardiology consultation, an ultrasound scan of the abdomen, dental X-ray & dental consultation, and a comprehensive blood test.',
    branch: 'Palayam',
    address: 'Near kerala university, palayam-Thiruvanathapuram',
    im: 'https://drgirijaslab.com/wp-content/uploads/2021/12/Alere-RT-2100T-Elisa-Reader-Analyser.jpg',
    nam: 'Bichromatic Reading Facility        ',
    des: 'Facility to load 36 wells at a time.Automatic 12/8 Strip Transportation.Flat,V and U bottom microwells can be read.405,450,492 and 630nm Common filters used.',
    giph: 'https://www.medivision.in/uploaded_files/blog/istockphoto-544125134-612x612_1667389657.jpg',
    link: 'Pre-Eclampsia Screening in Pregnancy',
    date:'30-OCTOBER-2022',

    para:'Unfortunately, high blood pressure can be dangerous to the mother and baby. Pre- eclampsia is one such high blood pressure (hypertension) disorder that can occur during pregnancy. Pre- eclampsia is a rare but serious condition that can develop at any time during pregnancy but is more common toward the end. High blood pressure is the first tell-tale sign. Pre-eclampsia occurs in around 1 in 50 pregnancies and is one of the most common life-threatening conditions occurring in pregnancy.Pre-eclampsia is thought to be caused by the placenta not developing properly due to a problem with the blood vessels supplying it. The exact cause isn t fully understood though.',
    head1:'Symptoms of Pre-Eclampsia    ',
    para1:'Pre-eclampsia rarely happens before the 20th week of pregnancy. Generally, the earlier pre-eclampsia develops, the more severe the condition will be.',
    head2:'Some of the risk factors for PE include:',
    para2:'maternal and paternal family history, previous pregnancy with pre-eclampsia,   multiple pregnancies (e.g., twins), maternal age (over 40 years), body mass index (BMI) over 30,pre-existing high blood pressure, diabetes, smoking, or kidney disease,systemic inflammation,ethnic origin.',
    head3:'Briefly    ',
    para3:'Pre-eclampsia is a condition that is specific to pregnancy and is diagnosed when a pregnant woman has high blood pressure and other clinical signs after 20 weeks of gestation. Although high blood pressure before pregnancy is one risk factor for preeclampsia, most women who develop preeclampsia never had high blood pressure and may have had low blood pressure before pregnancy.  , Pre-eclampsia can also develop postpartum. So, if you develop any of these symptoms after you give birth, check in with your healthcare provider immediately., If left untreated and unmonitored, preeclampsia can progress into more serious conditions that can put the mother and baby at risk for serious complications or even death.',
    doctor:'https://www.toplinemd.com/carreras-medical-center/wp-content/uploads/sites/12/2021/05/What-Is-an-Internist-800x534.jpg',
    docname:'Dr. Martin J (DIABATOLOGIST)',
  },
  {
    id: 10,
    img: 'cancer male.jpg',
    name: 'CANCER CHECKUP(MALE)',
    desc: 'AlphoFeto Protein (AFP),  Carcinoembryonic antigen (CEA),  Beta-human chorionic gonadotropin (Beta HCG), PSA -Prostate Specific Antige,GGT- Gamma GT',
    price: 'RS=3880',
    detail:
      'The Cancer Screening package offers a set of tests necessary for the early diagnosis of cancer in male. These include: Carcinoembryonic Antigen (CEA) test: A test to diagnose mainly the cancers of the large intestine and rectum. Alpha-fetoprotein (AFP): A blood test to diagnose liver cancer and some rare tumors',
    branch: 'Thampanoor',
    address: 'Near Trivandrum Central Railway station, Thampanoor-TVM',
    im: 'clinical.jpg',
    nam: 'Clinical Chemistry Analyzer        ',
    des: 'A Random Access,Fully-Automated,Walk Away Clinical Chemistry Analyzer with a throughput of up to 360 tests per hour(up to 450 tests per hour with ISE)',
    giph: 'https://www.medivision.in/uploaded_files/blog/istockphoto-964045016-612x612_1666780199.jpg',
    link: 'Things You Must Know About Multiple Myeloma',
    date:'25-OCTOBER-2022',

    para:'Cancer is a leading cause of death worldwide and it begins when the cells in our body grow out of control. Cells are present in nearly any part of the body that can cause cancer to easily spread to other areas. ,The type of cancer that forms in a particular type of white blood cell known as plasma cell causes Multiple Myeloma in human beings.  In a typical healthy body, the plasma cells fight infections by making antibodies that recognize and attack germs. Normal plasma cells are found in the bone marrow and are an important part of the immune system. When the plasma cells become cancerous and grow out of control, it leads to multiple myeloma. In multiple myeloma, rather than producing helpful antibodies, cancerous plasma cells get accumulated in the bone marrow and crowd out healthy blood cells which can cause complications.  The plasma cells make an abnormal protein (antibody) known by several different names, including monoclonal immunoglobulin, monoclonal protein (M-protein), M-spike, or paraprotein.',
    head1:'Symptoms of Multiple Myeloma    ',
    para1:'The signs and symptoms of multiple myeloma can vary and early in the disease, there may be none., When signs and symptoms do occur, they can include:, Bone pain, especially in your spine or chest,Nausea,Constipation,Loss of appetite,Mental fogginess or confusion,Fatigue,Frequent infections,Weight loss,Weakness or numbness in your legs,Excessive thirst',
    head2:'Other Screening Methods include    ',
    para2:'X-ray,Magnetic resonance imaging (MRI),Computed tomography (CT or CAT) scan ,Positron emission tomography (PET) or PET-CT scan,Bone marrow aspiration and biopsy,  Fat pad aspirate,Biomarker testing of the tumour,Cytogenetics,Fluorescence in situ hybridization (FISH),   Minimal residual disease (MRD) tests',
    head3:'To Summarise    ',
    para3:'If you re experiencing symptoms or know someone who has been experiencing it, treatment can help relieve pain, control complications of the disease, stabilize the condition, and slow the progress of multiple myeloma. , Consultation and diagnosis is the key to treating and management of multiple myeloma.  ',
    doctor:'https://texanent.com/wp-content/uploads/2021/04/an-ent-doctor-checking-up-on-a-woman.jpg', 
    docname:'Dr.Shanu Ali(ENT)',
  },
  {
    id: 11,
    img: 'cancer female.jpg',
    name: 'CANCER CHECKUP(FEMALE)',
    desc: 'Alpha Feto Protein (AFP),Carcinoembryonic antigen (CEA),CA-125,CA-19.9Beta-human chorionic gonadotropin (Beta HCG)',
    price: 'RS=5950',
    detail:
      'The Cancer Screening package offers a set of tests necessary for the early diagnosis of cancer in male. These include: Carcinoembryonic Antigen (CEA) test: A test to diagnose mainly the cancers of the large intestine and rectum. Alpha-fetoprotein (AFP): A blood test to diagnose liver cancer and some rare tumors.',
    branch: 'Thoduuzha',
    address: 'Near Shanthigiri college, Thodupuzha-Idukki',
    im: 'dry.jpg',
    nam: 'Dry Chemistry Blood Serum Analyzer        ',
    des: 'Dry chemistry blood serum analyzer,uses Kodak Ektachem DT slides to perform a number of discrete clinical tests on serum,plasma,or whole blood specimens',

    giph: 'https://www.medivision.in/uploaded_files/blog/istockphoto-1085627804-612x612_1663842709.jpg',
    link: 'Role of AMH in Infertility Treatment',
    date:'15-OCTOBER-2022',

    para:'Infertility is defined as not being able to get pregnant even after one year or longer of unprotected sex.,Women with infertility should consider consulting a reproductive endocrinologist—a doctor who specializes in managing infertility. A reproductive endocrinologist can also help women who have a recurrent pregnancy loss, defined as having two or more spontaneous miscarriages',
    head1:'AMH Test and its significance in infertility treatment    ',
    para1:'Women have a limited supply of eggs for their whole lives. Once the eggs are exhausted, there is no chance of conceiving naturally thereafter. Also, women generally become completely infertile after they have hit menopause. It is, therefore, important for women to identify and gauge their ovarian reserve if they ever plan to have a baby. Anti-Mullerian Hormone (AMH) is a protein hormone made by the cells lining the follicles (sacs that hold the eggs).  Low levels of AMH indicate low ovarian reserve, while optimal levels of AMH (4.00 – 6.80) suggest a bright future fertility probability. AMH is made in the reproductive tissues of both males and females. The role of AMH and whether levels are normal will depend on your age and gender.An AMH test measures the amount of anti-mullerian hormone (AMH) in your blood. Though both men and women produce AMH, healthcare providers frequently use the test in women, mainly to provide a snapshot of a woman’s reproductive health. Anti-Mullerian Hormone (AMH) test is a simple blood test that helps to analyse a womans ovarian reserve and diagnose problems such as PCOD, early menopause, or low ovarian reserve. ',
    head2:'When Do You Need an AMH Test?    ',
    para2:'The AMH test is helpful when:You are not conceiving for over six months  You are contemplating IVF or other fertility treatments since low AMH levels suggest a poor response to IVF You want to understand your current chances of getting pregnant    ',
    head3:'Conclusion    ',
    para3:'An AMH test checks a woman s ability to produce eggs that can be fertilized for pregnancy. AMH levels show how many potential egg cells are remaining in a woman, which is also known as the ovarian reserve. If the ovarian reserve is high, there’s a better chance of getting pregnant. This also indicates that a woman may also be able to wait months or years before trying to get pregnant.  On the other hand, if the ovarian reserve is low, it indicates that a woman will have trouble getting pregnant, and should not delay very long before trying to have a baby.Thus, AMH testing plays a vital role in determining what your chances are of conceiving a baby. If you are already seeing a fertility specialist, your doctor may use the test to predict whether you will respond well to treatment, such as in vitro fertilization (IVF).An optimal level of AMH is 4.00ng/ml – 6.80ng/ml.    ',
    doctor:'https://static.spacecrafted.com/d8084ebd368f4c10829ace74c8630750/i/df033a39ec3f425eb4cf48572cc19223/1/GCuCv727RiYFXYTGZA3v2p/Pharmacy%20Image%252851%2529.jpg',
    docname:'Dr. Priya S (PYSICIAN)',
  },
  {
    id: 12,
    img: 'liver.jpg',
    name: 'LIVER HEALTH SCREENING',
    desc: 'Alpha Feto Protein (AFP),Copper,HCV,Ultrasound Scanning-Whole Abdomen,CEA',
    price: 'RS=5450',
    detail:
      'Liver function tests are blood tests used to help diagnose and monitor liver disease or damage. The tests measure the levels of certain enzymes and proteins in your blood. Some of these tests measure how well the liver is performing its normal functions of producing protein and clearing bilirubin, a blood waste product. Other liver function tests measure enzymes that liver cells release in response to damage or disease. Abnormal liver function test results don t always indicate liver disease. Your doctor will explain your results and what they mean.',
    branch: 'Thrissur',
    address: 'Near medical college, Thrissur',
    im: 'freezing-microtome-500x500.webp',
    nam: 'Freezing Microtome        ',
    des: 'Freezing microtome is used for cutting thin to semi-thin sections of fresh,frozen tissue and semi-thin sections from industrial products such as some',
    giph: 'https://www.medivision.in/uploaded_files/blog/istockphoto-472034567-612x612_1663152318.jpg',
    link: 'Significance of Pregnancy Markers',
    date:'28-SEPTEMBER-2022',

    para:'In simple words, a marker is an indication. The presence of certain substances in the body becomes an indicator of certain conditions. Likewise, substances present in a pregnant woman’s blood serum can be used as markers during prenatal screening for certain fetal abnormalities like genetic diseases and birth defects.',
    head1:'The common maternal serum markers    ',
    para1:'Early in their pregnancy, all women are offered a screening of several blood markers. These can indicate increased fetal risk for certain genetic diseases and birth defects.     ',
    head2:'Double marker test    ',
    para2:'It is a maternal serum screening test that is performed during the first trimester, between 9 weeks and 12 weeks of pregnancy, and the ideal time is 11 weeks to 13 weeks.This test screens specifically for blood levels of both free beta-human chorionic gonadotrophin (beta-hCG) and pregnancy-associated plasma protein A (PAPP-A). Double marker test screening was previously recommended if you were over the age of 30 or have an elevated risk of chromosomal issues, such as if you have a family history of certain conditions. But today, a double marker test is mandatorily performed during the first trimester of pregnancy.     ',
    head3:'To Conclude',
    para3:'Prenatal screening allows for early detection of potentially life-threatening genetic illnesses. It tells the doctor if further probing is required and is a good starting point for monitoring the fetus and clearing any doubts surrounding its health.    ',
    doctor:'https://th.bing.com/th/id/R.d318ff1d63a38b91834e813aef12a9a5?rik=6IIy8XEV2u4WQA&riu=http%3a%2f%2fwww.max90hyperfuses.co.uk%2fwp-content%2fuploads%2f2018%2f08%2fThings-That-Oncologists-Need-To-Know-About-Their-Patients.jpg&ehk=QEOA4LyB6UXsJFLPwXh0chDbQgSTcpTa8cs4geUbXHc%3d&risl=&pid=ImgRaw&r=0',
    docname:'Dr.Ameer Muhammed(ENT)',
  },
  {
    id: 13,
    img: 'fert male.jpg',
    name: 'FERTILITY CHECKUP (MALE)',
    desc: 'DHEA-s, FSH, LH, Prolactin, Testosterone, Semen Detailed Analysis,  C-Peptide - Fasting,C-Peptide - PP',
    price: 'RS=4480',
    detail:
      'If you might have a fertility problem, your doctor will want to perform a complete history and physical, as well as several tests to find out what may be causing your infertility.',
    branch: 'Kannur',
    address: 'Near mahi Bypass-Kannur',
    im: 'biomeriux-mini-vidas-immunoassay-analyzer-500x500.webp',
    nam: 'Biomerieux Mini Vidas        ',
    des: 'The Biomerieux Mini Vidas Automated Immunoassay Analyzer system is a perfect alternative for a physicians office lab setting.This system brings productivity ',
    giph: 'https://www.medivision.in/uploaded_files/blog/istockphoto-1352255861-612x612_1661252794.jpg',
    link: 'Cervical Cancer and Screening Methods',
    date:'18-AUGUST-2022',

    para:'Allergies are our immune system’s reaction to a normally harmless foreign substance (known as an allergen) like -bee venom, pet dander, pollen, or a kind of/ few kinds of food. The manner by which the body responds to the allergen is called an allergic reaction. ',
    head1:'Allergy Diagnosis    ',
    para1:'Many times, you may not know what is causing your allergy symptoms. Information from allergy tests will help your doctor develop an allergy treatment plan that includes allergen avoidance, medications, or allergy shots (immunotherapy).   ',
    head2:'Food Allergy Test    ',
    para2:'Food allergy testing is used to find out if a person has an allergy to a specific food. It may also be used to find out whether it is a true allergy or, a sensitivity to a food. Food sensitivity, which is also known as food intolerance, is often confused with a food allergy. The two conditions commonly have similar symptoms, but complications can be very different.    ',
    head3:'Conclusion: The Importance of Testing Your Allergies    ',
    para3:'Allergy testing can help avoid serious health implications or overreactions and it may relieve some of your stress if you find out you are allergy-free. Allergy testing is important and beneficial because it tells you exactly what to stay away from.Simply looking at history and patient reports to predict allergies is not reliable. Allergy testing can inform patients exactly what to stay away from and avoid overreactions.    ',
    doctor:'https://jobstars.com/wp-content/uploads/2017/03/Onepixel_1744047-1200x800.jpg',
    docname:'Dr. Arun Kumar(PHYSICIAN)',
  },
  {
    id: 14,
    img: 'fertility female.jpg',
    name: 'FERTILITY CHECKUP (FEMALE)',
    desc: 'DHEA -s,Estradio, FSH, LH. Prolactin, Anti Mullerian Hormone, Insulin - Fasting',
    price: 'RS=6380',
    detail:
      'If you might have a fertility problem, your doctor will want to perform a complete history and physical, as well as several tests to find out what may be causing your infertility.',
    branch: 'Vadavathoor',
    address: 'Near Girideepam College-Vadavathoor-Kanjukkuzhi-Kottayam',
    im: 'abx.jpg',
    nam: 'The ABX Micros 60    ',
    des: 'The ABX Micros 60 3 Part Differential Hematology Analyzer is designed for easy to use,accurate and reliable.The Micros 60 combines the accuracy and reliability ',
    giph: 'https://www.medivision.in/uploaded_files/blog/istockphoto-896115392-612x612_1660932907.jpg',
    link: 'Allergy - Symptoms and Tests',
    date:'05-AUGUST-2022',

    para:'The sugar present in your blood is called glucose. Insulin (a hormone made by the pancreas) helps glucose from the food entering your cells to be used for energy. In certain cases, your body doesn’t make enough or any insulin or doesn’t use insulin well. In such a situation, Glucose stays in your blood and doesn’t reach your cells.    ',
    head1:'An A1C test helps to measure how much glucose is bound    ',
    para1:'This test shows the average level of glucose in your blood for the past 3 months. If your glucose levels have been high over the recent weeks, your haemoglobin A1c test will also be higher. The A1C test is useful in diagnosing type 1 and type 2 diabetes. If you have been living with diabetes, the test also helps to monitor how well you have been managing blood sugar levels. An A1C test result reflects your average blood sugar level for the past two to three months. The higher your A1C level is, the poorer your blood sugar control and the higher your risk of diabetes complications.    ',
    head2:'Do Lifestyle Modifications Score Over Medications in Managing HbA1c?    ',
    para2:'Studies were conducted to analyse if increasing the quantity and quality of physical activity, will affect the overall glycaemic control independently or in combination with hypoglycaemic drugs. The majority of studies (that supplement weight reduction and exercise programs with appropriate drug therapy) were done. The objective of the assessment was to know the effect of how structured exercise training and unstructured physical activity intervenes with glycaemic control.The treatment guidelines stressed lifestyle modification, in terms of increasing the quantity and quality of physical activity to achieve target glycemia in patients with type 2 diabetes mellitus.    ',
    head3:'',
    para3:'',
     doctor:'https://th.bing.com/th/id/OIP.zje6zNirx4OFJpvrq5ECOAHaE8?pid=ImgDet&rs=1',
     docname:'Dr.Vyshak M (ONCOLOGIST)',
  },
  {
    id: 15,
    img: 'cardiac.jpg',
    name: 'Cardiac Screening',
    desc: 'CBC+ ESR,Fasting Blood Glucose,PP Blood Glucose,Nefro-C (Cystatin-C),Microalbuminuria,Lipid Profile Tests,Lipoprotein(a)',
    price: 'RS=6450',
    detail:
      'During a heart health checkup, your doctor will talk to you about how you’re feeling and offer you screening tests to assess your cardiovascular health and risk factors. Your cardiovascular system includes your heart and blood vessels.',
    branch: 'Kadavanthra',
    address: 'Near Chiyang Restaurannt, Kadavanthra-Cochin',
    im: 'micotome-pathological-item-500x500.webp',
    nam: 'Leica Rotary Microtome ',
    des: 'Consistently cut high-quality sections with a manual,semi-automated or fully automated Leica rotary microtome.Deliver precise sections,',
    giph: 'https://www.medivision.in/uploaded_files/blog/istockphoto-637422184-612x612_1659164867.jpg',
    link: 'Is Lifestyle Modifications Scoring ?',
    date:'30-JULY-2022',

    para:'The two bean-shaped organs (about the size of a fist), that are located just below the rib cage, one on each side of your spine are called Kidneys. The function of the kidney is to filter your blood, removing wastes and extra water. The waste in the form of urine flows from the kidneys to the bladder through two thin tubes called ureters. Your kidneys are an essential organ and the major component of your urinary tract.    ',
    head1:'What is Kidney Failure?    ',
    para1:'Kidney failure also referred to as renal failure or renal dysfunction means one or both kidneys can no longer function well on their own. Sometimes the failure is temporary and comes on quickly. It can also be a chronic condition that worsens slowly over a long time. During a renal dysfunction or kidney failure, one or both the kidneys stop working and are not able to remove waste and extra water from the blood and keep body chemicals in balance.    ',
    head2:'Causes of Kidney Failure    ',
    para2:'Diabetes and high blood pressure are the most common causes of kidney failure. Sometimes, kidney failure also happens quickly due to any unforeseen cause. Acute kidney failure (or acute kidney injury) is when the kidneys lose function suddenly (within hours or days). This type of kidney failure could be temporary. Common causes of acute kidney failure can include:    ',
    head3:'Is It Possible to Prevent Kidney Failure?    ',
    para3:'Though kidney failure from chronic kidney disease can’t be reversed, you can do things that help to preserve kidney function. Healthy habits will slow down how quickly kidneys lose their functional abilities. If you are already a victim of chronic kidney disease or kidney failure, you should: Monitor your kidney function., Keep your blood sugar levels under control.,  Keep your blood pressure levels in a normal range.    Avoid smoking.Make healthy diet choices and limit foods high in protein and sodium    ',
    doctor:'https://viewofhealth.com/wp-content/uploads/2020/04/Dr-Reading-scaled.jpg',
    docname:'Dr.Jinu George(CARDIOLOGIST)',
  },
  {
    id: 16,
    img: 'exc fe.jpg',
    name: 'EXECUTIVE HEALTH CHECKUP-LADIES',
    desc: 'Fasting Blood Glucose,Blood Glucose, Lipid Profile Tests, Liver Function Tests, Gamma GT,Kidney Function Tests,Thyroid Function Tests (T3,T4,TSH),HIV I & II',
    price: 'RS=4880',
    deatil:
      'According to the latest researches on the subject, fast changing lifestyles, work related pressure and handling information overflow through increasing social media activities all have contributed to a new medical condition called the Busy Life Syndrome, which is believed as leading to short term lapses in memory apart from the overall harm that it causes for other body functions.',
    branch: 'Adoor',
    address: 'Near Marthoma Youth Center ,Adoor-Pathanamthitta',
    im: 'culture.jpg',
    nam: 'Bactec - Blood Culture    ',
    des: 'BD BACTEC blood culture media.For use with BD BACTEC instrumented blood culture systems,the BD BACTEC line of blood culture media permits screening',
    giph: 'https://www.medivision.in/uploaded_files/blog/istockphoto-928819946-612x612_1658312180.jpg',
    link: 'Early Symptoms of Renal Dysfunction',
    date:'18-JULY-2022',

    para:'A fever is the body’s natural response to infection and is a higher-than-normal body temperature. A low-grade fever may not be a cause for concern, but a temperature of 102°F and above should be treated.     ',
    head1:'What Causes Fever?    ',
    para1:'The response to diseases by your immune system causes your body temperature to rise. This condition prompts complex processes producing more heat and restricting heat loss. Fever or elevated body temperature is caused by: A viral infection A bacterial infection ,Heat exhaustion Certain inflammatory conditions such as rheumatoid arthritis ,A cancerous (malignant) tumour,Some medications like antibiotics and drugs used to treat high blood pressure or seizures ,Some immunizes like diphtheria, tetanus and acellular pertussis (DTaP), pneumococcal or COVID vaccine',
    head2:'Types Of Fevers    ',
    para2:'Dengue fever-This kind of fever is classified as a mosquito-borne viral disease occurring in tropical and subtropical areas. Getting infected with the virus a second time causes a significantly greater risk of developing severe disease.  Leptospirosis Fever-This is a bacterial disease that affects humans and animals and is caused by bacteria of the genus Leptospira. In certain cases, some infected persons may have no symptoms at all.',  
    head3:' Conclusion    ',
    para3:'Fever is a general sign that something is wrong with the body. We usually tend to take it lightly or do self-medication which is not the right way to deal with it. Knowing the underlying cause of fever is necessary not only for its treatment but also to avoid complications. Always consult your physician and take the prescribed tests without fail to determine and commence the right medication.    ',
    doctor:'https://shoesfordoctors.com/wp-content/uploads/2018/08/Depositphotos_74956115_s-2019-min-1.jpg',
    docname:'Dr.Manu Jacob Varghese(SURGEON)',
  },
  {
    id: 17,
    img: 'exc mm.jpg',
    name: 'EXECUTIVE HEALTH CHECKUP-MEN',
    desc: 'Fasting Blood Glucose,PP Blood Glucose,Lipid Profile Tests,HbA1c,Creatinine,Calcium,Prostate Specific Antigen (PSA)',
    price: 'RS=4820',
    detail:
      'According to the latest researches on the subject, fast changing lifestyles, work related pressure and handling information overflow through increasing social media activities all have contributed to a new medical condition called the Busy Life Syndrome, which is believed as leading to short term lapses in memory apart from the overall harm that it causes for other body functions.',
    branch: 'Palakkad',
    address: 'Near NIT Palakkad',
    im: 'urine.jpg',
    nam: 'Cobas 6500    ',
    des: 'The cobas 6500 urine analyzer series provides a fully automated solution on a modular platform for laboratories processing 100-1000 urine samples per day.',
    giph: 'https://www.medivision.in/uploaded_files/blog/[downloader-la]-62ca984a4bce6_1657444504.jpg',
    link: 'Variety of Fevers and Classical Symptoms',
    date:'22-JUNE-2022',


    para:'',
    head1:'',
    para1:'',
    head2:'',
    para2:'',
    head3:'',
    para3:'',
    doctor:'https://thumbs.dreamstime.com/b/young-female-doctor-gray-background-keeps-folder-documents-thinks-to-write-there-displaying-one-139768565.jpg',
    docname:'Dr.Anita John(HEPATOLOGIST)',
  },
  {
    id: 18,
    img: 'lady.jpg',
    name: 'HEALTHY LADY CHECKUP PACKAGE(B)',
    desc: 'Fasting Blood Glucose,Blood Glucose, Lipid Profile Tests, CBC + ESR,Ultrasound Scan- Whole Abdomen, Tread Mill TestLiver Function Tests',
    price: 'RS=4150',
    detail:
      'Regular health exams and tests can help find problems before they start. They also can help find problems early, when your chances for treatment are better. As a woman, you need some special exams and screenings.',
    branch: 'Kuttippuram',
    address: 'Near Kuttippuram Busstand',
    im: 'cobas6000.jpg',
    nam: 'The Cobas 6000 Analyzer    ',
    des: 'The cobas 6000 analyzer series is a member of the cobas family of analyzers.This solution is designed for laboratories which typically produce from 500000 to 2.5',
    giph: 'https://www.medivision.in/uploaded_files/blog/istockphoto-1385972198-612x612_1655400238.jpg',
    link: 'NAFLD ',
    date:'05-JUNE-2022',

    para:'',
    head1:'',
    para1:'',
    head2:'',
    para2:'',
    head3:'',
    para3:'',
    doctor:'https://blogs.davita.com/medical-insights/wp-content/uploads/sites/8/2017/06/iStock-508387030.jpg',
    docname:'Dr.Smitha S Nair(PEDIATRICIAN)',
  },
];
